import os
import json
from datasets import load_dataset, Dataset, concatenate_datasets
from huggingface_hub import login

def upload_and_extend_dataset():
    # 1. Authenticate
    hf_token = os.environ.get("HF_TOKEN")
    if not hf_token:
        raise ValueError("HF_TOKEN environment variable is missing.")
    login(token=hf_token)

    repo_id = "neetmehta/GujaratiTextDataset"
    data_file = "data/gujarati_corpus.jsonl"

    if not os.path.exists(data_file):
        print(f"No new data generated by the crawler ({data_file} not found).")
        return

    # 2. Load the newly scraped data into memory
    print("Loading newly scraped records...")
    with open(data_file, "r", encoding="utf-8") as f:
        new_records = [json.loads(line) for line in f]
    
    if not new_records:
        print("Scraped data file is empty. Exiting.")
        return

    # 3. Try to load the existing dataset from Hugging Face Hub
    try:
        print(f"Attempting to fetch existing dataset from {repo_id}...")
        existing_dataset = load_dataset(repo_id, split="train")
        
        # Create a set of URLs already present in the Hub dataset to prevent duplicates
        existing_urls = set(existing_dataset['url'])
        
        # Filter the new records to only keep unseen URLs
        unique_new_records = [rec for rec in new_records if rec['url'] not in existing_urls]
        
        if not unique_new_records:
            print("No new unique articles found today. Skipping upload.")
            return
            
        print(f"Found {len(unique_new_records)} new unique records!")
        unique_new_dataset = Dataset.from_list(unique_new_records)
        
        # Combine the old dataset with the new unique records
        final_dataset = concatenate_datasets([existing_dataset, unique_new_dataset])
        print(f"Extending dataset. Previous size: {len(existing_dataset)}, New size: {len(final_dataset)}.")

    except Exception as e:
        # If the dataset doesn't exist yet (e.g., the very first run), handle the exception
        print(f"Could not load existing dataset (it might be the first run): {e}")
        final_dataset = Dataset.from_list(new_records)
        print(f"Creating a new dataset with {len(final_dataset)} records.")

    # 4. Push the combined (extended) dataset back to Hugging Face
    print(f"Pushing extended dataset to Hugging Face Hub at {repo_id}...")
    final_dataset.push_to_hub(repo_id)
    print("Upload complete!")

if __name__ == "__main__":
    upload_and_extend_dataset()